Repository Nexters/landlords-server, pull requests merged in 2020-07, with the labels that each got.

#16 Feature/room crawling
  .vscode/launch.json
  Pipfile
  Pipfile.lock
  requirements.txt
  src/apps/rooms/models/domain.py
  src/apps/rooms/models/domain/__init__.py
  src/apps/rooms/models/domain/dabang.py
  src/apps/rooms/models/domain/landlords.py
  src/apps/rooms/models/entity/__init__.py
  src/apps/rooms/models/requests.py
  src/apps/rooms/models/responses.py
  src/apps/rooms/routes.py
  src/apps/rooms/services.py
  tests/function/apps/__init__.py
  tests/function/apps/rooms/__init__.py
  tests/function/apps/rooms/test_services.py
Labels: enhancement

#17 feat(oauth): 구글 oauth2 인증을 통한 회원 인증 기능 추가
  .env
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  Pipfile.lock
  private_key
  public_key
  src/apps/auth/__init__.py
  src/apps/auth/exceptions.py
  src/apps/auth/models/__init__.py
  src/apps/auth/models/domain/__init__.py
  src/apps/auth/models/domain/oauth.py
  src/apps/auth/models/domain/tokens.py
  src/apps/auth/models/domain/user.py
  src/apps/auth/models/entity/__init__.py
  src/apps/auth/models/responses.py
  src/apps/auth/routes/__init__.py
  src/apps/auth/routes/oauth.py
  src/apps/auth/routes/token.py
  src/apps/auth/services.py
  src/asgi.py
  src/core/config.py
  src/core/exceptions.py
  src/core/handlers.py
  src/main.py
Labels: enhancement

#18 refactor(oauth): 구글 oauth2 개편
  Pipfile
  Pipfile.lock
  google.env.sample
  mypy.ini
  requirements.txt
  src/apps/auth/exceptions.py
  src/apps/auth/models/__init__.py
  src/apps/auth/models/domain/__init__.py
  src/apps/auth/models/domain/oauth.py
  src/apps/auth/models/domain/tokens.py
  src/apps/auth/models/domain/user.py
  src/apps/auth/models/responses.py
  src/apps/auth/routes/__init__.py
  src/apps/auth/routes/oauth.py
  src/apps/auth/routes/token.py
  src/apps/auth/services.py
  src/apps/oauth/__init__.py
  src/apps/oauth/client.py
  src/apps/oauth/entity.py
  src/apps/oauth/models.py
  src/apps/oauth/services.py
  src/apps/rooms/routes.py
  src/asgi.py
  src/core/config.py
  src/core/handlers.py
  src/main.py
Labels: enhancement

#19 fix(rooms): 방 크롤링 예외처리 추가
  src/apps/rooms/exceptions.py
  src/apps/rooms/models/domain/dabang.py
  src/apps/rooms/models/entity/__init__.py
  src/apps/rooms/routes.py
  src/apps/rooms/services.py
  src/core/exceptions.py
  src/core/handlers.py
  src/main.py
  tests/function/apps/rooms/test_services.py
Labels: enhancement

#20 feat(persona): 임차인 페르소나 분석을 위한 API 추가 (질문 리스트, 응답 저장, 페르소나 반환)
  src/apps/oauth/exceptions.py
  src/apps/oauth/models.py
  src/apps/oauth/services.py
  src/apps/persona/__init__.py
  src/apps/persona/exceptions.py
  src/apps/persona/models/__init__.py
  src/apps/persona/models/domain.py
  src/apps/persona/models/entity.py
  src/apps/persona/models/responses.py
  src/apps/persona/routes.py
  src/apps/persona/services.py
  src/apps/rooms/routes.py
  src/routes/__init__.py
  tests/conftest.py
  tests/unit/apps/persona/__init__.py
  tests/unit/apps/persona/services/__init__.py
  tests/unit/apps/persona/services/test_question.py
Labels: enhancement

#22 refactor(config): rsa 대칭키 file read -> env, database engine 제공 함수로 변경
  .env
  Dockerfile
  docker-compose.yaml
  private_key
  public_key
  src/core/config.py
  src/core/database.py
Labels: refactor

#28 feat(jwk): jwk 추가
  Pipfile
  Pipfile.lock
  requirements.txt
  src/apps/oauth/models.py
  src/apps/oauth/routes.py
  src/apps/oauth/services.py
  src/asgi.py
  src/core/handlers.py
  src/main.py
Labels: feature

#26 feat(checklist): 체크리스트 생성, 응답내역 불러오기 및 체크삭제 api 추가
  requirements.txt
  src/apps/checklist/__init__.py
  src/apps/checklist/exceptions.py
  src/apps/checklist/models/__init__.py
  src/apps/checklist/models/domain.py
  src/apps/checklist/models/entity.py
  src/apps/checklist/models/requests.py
  src/apps/checklist/models/responses.py
  src/apps/checklist/routes.py
  src/apps/checklist/services.py
  src/apps/rooms/exceptions.py
  src/apps/rooms/routes.py
  src/routes/__init__.py
  src/routes/health.py
Labels: feature

#29 chore: 서비스명 설정 추가
  src/__init__.py
  src/asgi.py
  src/main.py
  tests/conftest.py
Labels: documentation
