Repository Nexters/landlords-server, pull requests merged in 2020-08, with the labels that each got.

#31 feat(token-cookie): web과 통합을 위한 token 처리
  src/apps/oauth/client.py
  src/core/config.py
Labels: feature

#32 feat(cors): cors 처리 추가
  src/asgi.py
  src/core/config.py
Labels: feature

#33 docs: update readme
  README.md
Labels: documentation

#34 ci(deploy): 배포 스크립트 수정
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: config

#36 fix(cookie): cookie 생성 시 domain 추가
  src/apps/oauth/client.py
  src/core/config.py
Labels: bug

#35 fix(room): 이미지 컬럼 추가 및 SalesType 반환
  requirements.txt
  src/apps/rooms/models/domain/dabang.py
  src/apps/rooms/models/domain/landlords.py
  src/apps/rooms/models/domain/zigbang.py
  src/apps/rooms/models/entity/__init__.py
  src/apps/rooms/models/responses.py
  src/apps/rooms/routes.py
Labels: enhancement

#39 fix(checklist): 체크리스트 방계약상태 컬럼 추가
  src/apps/checklist/models/domain.py
  src/apps/checklist/models/entity.py
  src/apps/checklist/routes.py
  src/apps/checklist/services.py
Labels: enhancement

#40 fix(auth): get_current_user 버그 수정
  src/apps/oauth/services.py
Labels: bug

#41 fix(room): 전용면적, 층, 엘리베이터, 관리비 항목 추가
  src/apps/rooms/models/domain/dabang.py
  src/apps/rooms/models/domain/landlords.py
  src/apps/rooms/models/domain/zigbang.py
  src/apps/rooms/models/entity/__init__.py
  tests/function/apps/rooms/test_services.py
Labels: enhancement

#42 fix: 방 매물 저장, 오타, 체크리스트 nullable 추가
  src/apps/checklist/models/domain.py
  src/apps/checklist/models/entity.py
  src/apps/persona/models/domain.py
  src/apps/rooms/models/domain/landlords.py
  src/apps/rooms/models/entity/__init__.py
Labels: bug

#46 refactor(users): 마이페이지를 위한 users 리팩토링
  .env
  src/apps/checklist/models/entity.py
  src/apps/checklist/routes.py
  src/apps/checklist/services.py
  src/apps/oauth/client.py
  src/apps/oauth/models/domain/google.py
  src/apps/oauth/models/domain/landlords.py
  src/apps/oauth/routes.py
  src/apps/oauth/services.py
  src/apps/persona/models/entity.py
  src/apps/persona/routes.py
  src/apps/persona/services.py
  src/apps/rooms/models/entity/__init__.py
  src/apps/rooms/routes.py
  src/apps/users/__init__.py
  src/apps/users/exceptions.py
  src/apps/users/models/__init__.py
  src/apps/users/models/domain.py
  src/apps/users/models/entity.py
  src/apps/users/models/requests.py
  src/apps/users/models/responses.py
  src/apps/users/routes.py
  src/apps/users/services.py
  src/routes/__init__.py
Labels: enhancement, feature

#48 fix(rooms): 기본 room uid 수정, 관리비 최대 값 수정
  src/apps/rooms/models/domain/landlords.py
Labels: bug

#49 fix(users): google oauth 로그인 버그 수정
  src/apps/oauth/client.py
  src/apps/oauth/models/domain/google.py
  src/apps/users/models/domain.py
  src/apps/users/services.py
Labels: bug

#50 fix(users): 로그인 버그 수정
  src/apps/users/models/domain.py
Labels: bug

#51 chore(test-mysql-init): test mysql container 최초 구동 시 sql 진입점 추가
  docker-compose.yaml
  infra/mysql/initdb/init.sql
Labels: config

#53 fix(delete-rooms): 방 삭제 버그 수정
  docker-compose.yaml
  infra/mysql/initdb/init.sql
  src/apps/checklist/models/entity.py
Labels: bug

#52 fix(persona): 페르소나 로직 추가 및 체크리스트 항목 매핑 수정중
  src/apps/checklist/models/domain.py
  src/apps/checklist/models/entity.py
  src/apps/checklist/routes.py
  src/apps/checklist/services.py
  src/apps/persona/models/const.py
  src/apps/persona/models/domain.py
  src/apps/persona/models/entity.py
  src/apps/persona/models/responses.py
  src/apps/persona/routes.py
  src/apps/persona/services.py
Labels: enhancement

#55 refactor(create-room): 방의 uid는 서버에서 생성하므로 request에서 제거
  src/apps/rooms/models/domain/dabang.py
  src/apps/rooms/models/domain/landlords.py
  src/apps/rooms/models/domain/zigbang.py
  src/apps/rooms/routes.py
  tests/function/apps/rooms/test_services.py
Labels: enhancement
